name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev"]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/mlqda_project/requirements.txt
        python -m spacy download en
        pip show pdflatex
    - name: Install texlive
      run: |
        wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
        mkdir texmf
        tlmgr init-usertree
        sudo tlmgr install lastpage
        sudo tlmgr install soul
        sudo tlmgr install xcolor
        sudo tlmgr install ltablex
        which tlmgr
    - name: Migrate database
      run: |
        python src/mlqda_project/manage.py makemigrations
        python src/mlqda_project/manage.py migrate
    - name: Run Tests
      run: |
        python src/mlqda_project/manage.py test mlqda
    - name: Coverage Report
      run: |
         coverage run src/mlqda_project/manage.py test mlqda
         coverage report -m


  linting:
      runs-on: ubuntu-latest
      strategy:
        max-parallel: 4
        matrix:
          python-version: [3.8, 3.9]
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/mlqda_project/requirements.txt
          pip install flake8
      - name: Run Linter
        run: |
          cd src/mlqda_project/
          flake8 --max-line-length 99
